# Master Orchestrator Configuration

# Logging configuration
logging:
  level: DEBUG
  file: orchestrator.log
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  console: true

# Agent endpoints
agents:
  frontend:
    endpoint: "/agents/frontend"
    timeout: 60
  backend:
    endpoint: "/agents/backend"
    timeout: 120
  database:
    endpoint: "/agents/database"
    timeout: 90
  testing:
    endpoint: "/agents/testing"
    timeout: 300
  devops:
    endpoint: "/agents/devops"
    timeout: 60

# Retry configuration
retry:
  max_attempts: 3
  backoff_factor: 1
  initial_delay: 1  # seconds

# Task management
tasks:
  max_concurrent: 5
  priority_threshold: 3  # Tasks with priority <= this value are considered high priority

# Code aggregation
code_aggregation:
  temp_dir: ".temp_aggregation"
  merge_strategy: "union"  # Options: union, recursive, ours, theirs
